**🌟 Exercise 1 : Array Creation and Manipulation**

In [10]:
#Create a 1D NumPy array containing numbers from 0 to 9.
import numpy as np

one_array = np.arange(10)
one_array

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

**🌟 Exercise 2 : Type Conversion and Array Operations**

In [2]:
#Convert a list into a NumPy array and its data type into an integer
lis = [3.14, 2.17, 0, 1, 2]
new_array = np.array(lis)

int_array = new_array.astype(int)

int_array

array([3, 2, 0, 1, 2])

**🌟 Exercise 3 : Working with Multi-Dimensional Arrays**

In [3]:
#Create a 3x3 NumPy array with values ranging from 1 to 9
array_2D = one_array.reshape(3, 3)

array_2D

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

**🌟 Exercise 4 : Creating Multi-Dimensional Array with Random Numbers**

In [4]:
#Create a 2D NumPy array of shape (4, 5) filled with random numbers.
matrix = np.round(np.random.rand(4, 5), 2)
matrix

array([[0.34, 0.75, 0.05, 0.81, 0.98],
       [0.2 , 0.76, 0.93, 0.53, 0.06],
       [0.5 , 0.51, 0.32, 0.4 , 0.29],
       [0.51, 0.67, 0.5 , 0.56, 0.74]])

**🌟 Exercise 5 : Indexing Arrays**

In [7]:
#Select the second row from a given 2D NumPy array.
array = np.array([[21,22,23,22,22],[20, 21, 22, 23, 24],[21,22,23,22,22]])

print(array[1])

[20 21 22 23 24]


**🌟 Exercise 6 : Reversing elements**

In [11]:
# Reverse the order of elements in a given 1D NumPy array (first element becomes last).
sorted_array = np.sort(one_array)[::-1]

sorted_array

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

**🌟 Exercise 7 : Identity Matrix**

In [12]:

identity_matrix = np.eye(4)

print(identity_matrix)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


**🌟 Exercise 8 : Simple Aggregate Funcs**

In [ ]:
#Find the sum and average of a given 1D array.
arr = np.arange(10)  # [0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

total = np.sum(arr)
average = np.mean(arr)

print(f"Sum: {total}, Average: {average}")

**🌟 Exercise 9 : Create Array and Change its Structure**

In [ ]:
#Create a NumPy array with elements from 1 to 20; then reshape it into a 4x5 matrix.
arr = np.arange(1, 21)          # [1, 2, 3, ..., 20]
matrix = arr.reshape(4, 5)

print(matrix)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]


**🌟 Exercise 10 : Conditional Selection of Values**

In [15]:
#Extract all odd numbers from a given NumPy array.
arr = np.arange(1, 11)  # [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

odd_numbers = arr[arr % 2 != 0]

odd_numbers

array([1, 3, 5, 7, 9])